<template><view class="consult-page"><ConsultationAside :module="draft.module"/><view class="main"><AppHeader/><view class="stepbar"><text class="active">01<br/>了解需求</text><i></i><text>02<br/>上传照片</text><i></i><text>03<br/>获取提案</text></view><view class="form"><section><text class="idx">01</text><view class="question"><view class="section-title">{{config.feelingTitle}}</view><view class="lead">{{config.feelingLead}}</view><view class="styles"><view v-for="(s,i) in config.styles" :key="s.value" class="style" :class="{chosen:selected.includes(s.value)}" @click="toggleStyle(s.value)"><image class="image-monochrome" :src="styleImages[i]" mode="aspectFill"/><view class="shade"></view><text class="selected-projection">{{s.value}}</text><view class="selected-mark">✓ 已选择</view><text class="style-name">{{s.value}}</text><small>{{s.desc}}</small></view></view></view></section><section><text class="idx">02</text><view class="question"><view class="section-title">{{config.effortTitle}}</view><view class="lead">{{config.effortLead}}</view><view class="time-options"><text v-for="t in config.efforts" :key="t" :class="{active:effort===t}" @click="effort=t">{{t}}</text></view></view></section><section><text class="idx">03</text><view class="question"><view class="section-title">{{config.noteTitle}}</view><wd-textarea v-model="note" :maxlength="300" show-word-limit :placeholder="config.placeholder"/></view></section><view class="footer"><template v-if="draft.module==='hair'"><wd-switch v-model="beauty"/><text>同时考虑眉形与自然妆容协调</text></template><view class="spacer"></view><view class="editorial-btn" @click="next">下一步 · 上传照片　→</view></view></view></view></view></template>

<script setup lang="ts">
import{computed,ref}from'vue';import{onLoad,onShow}from'@dcloudio/uni-app';import{draft,startConsultation}from'../../state';
const hairStyleImages=[1,2,3,4].map(i=>`/static/design/hair-style-${i}.png`);
const configs={
 hair:{feelingTitle:'你希望发型呈现怎样的状态？',feelingLead:'结合日常通勤、社交和打理习惯，可选择一个或多个方向。',styles:[['自然松弛','轻盈有层次，日常不刻意'],['清爽利落','轮廓干净，看起来更精神'],['温柔知性','线条柔和，兼顾亲和与质感'],['鲜明时髦','重点明确，保留个人辨识度']],effortTitle:'每天愿意花多少时间打理？',effortLead:'用于平衡造型效果与日常可执行性。',efforts:['几乎不打理','5 分钟以内','10–15 分钟','可以精细打理'],noteTitle:'发型或发色有什么一定要保留或避免的吗？',placeholder:'例如：不染发、保留长度、适合通勤、不要遮眼睛……'},
 skin:{feelingTitle:'你更期待怎样的肌肤状态？',feelingLead:'从日常可见状态出发，选择你最希望优先改善的方向。',styles:[['清透自然','减少厚重感，保留真实肤质'],['匀净明亮','改善暗沉感，看起来更有精神'],['稳定舒适','温和低负担，优先维持稳定'],['细腻光泽','提升细腻度与自然通透感']],effortTitle:'每天愿意投入多少护理时间？',effortLead:'建议限定在非医疗、可持续执行的日常护理范围。',efforts:['极简 3 分钟','基础 5 分钟','完整 10 分钟','可分早晚护理'],noteTitle:'有哪些肤质感受、产品偏好或需要避开的成分？',placeholder:'例如：容易敏感、避免香精、希望步骤简单、只接受基础护理……'},
 outfit:{feelingTitle:'你希望穿搭传达怎样的状态？',feelingLead:'结合通勤、休闲和社交场景，选择更接近你生活方式的方向。',styles:[['松弛简约','自然克制，单品容易重复搭配'],['利落通勤','线条清晰，专业但不过分正式'],['柔和雅致','材质轻盈，层次细腻有质感'],['鲜明时髦','重点突出，形成稳定辨识度']],effortTitle:'日常更适合哪种搭配方式？',effortLead:'用于平衡风格完整度、衣橱复用率与准备时间。',efforts:['拿取即穿','5 分钟搭配','按场景搭配','愿意精细搭配'],noteTitle:'有哪些场景、版型或单品需要保留或避开？',placeholder:'例如：以通勤为主、不穿高跟鞋、需要方便乘坐地铁、保留现有外套……'},
 makeup:{feelingTitle:'你希望妆容呈现怎样的状态？',feelingLead:'结合通勤、约会和正式场合，可选择一个或多个常用方向。',styles:[['清透裸妆','保留真实肤质，轻盈不厚重'],['利落通勤','眉眼干净，快速提升精神感'],['柔和气色','低对比配色，自然提升亲和感'],['鲜明重点','突出唇眼重点，增强个人辨识度']],effortTitle:'每天愿意花多少时间完成妆容？',effortLead:'建议会按时间给出清晰的步骤、重点和产品优先级。',efforts:['3 分钟快速妆','5 分钟日常妆','10–15 分钟','可以完整精细妆'],noteTitle:'有哪些妆容重点、产品偏好或需要避开的做法？',placeholder:'例如：不使用假睫毛、适合通勤、容易晕妆、希望弱化眼下……'}
} as const;
type Module=keyof typeof configs;
const pageModule=ref<Module>('hair');let sessionId=-1;
const config=computed(()=>{const c=configs[pageModule.value];return{...c,styles:c.styles.map(([value,desc])=>({value,desc}))}});
const styleImages=computed(()=>pageModule.value==='hair'?hairStyleImages:[1,2,3,4].map(i=>`/static/design/${pageModule.value}-style-${i}.png`));
const selected=ref<string[]>([]),effort=ref<string>(''),note=ref(''),beauty=ref(false);
function reset(){startConsultation(pageModule.value);sessionId=draft.sessionId;selected.value=[];effort.value=config.value.efforts[1];note.value='';beauty.value=false}
onLoad(query=>{const module=String(query?.module||'hair');pageModule.value=Object.prototype.hasOwnProperty.call(configs,module)?module as Module:'hair';reset()});
onShow(()=>{if(sessionId!==draft.sessionId)reset()});
function toggleStyle(v:string){const i=selected.value.indexOf(v);i<0?selected.value.push(v):selected.value.splice(i,1)}
function next(){if(sessionId!==draft.sessionId)return;draft.includeBeauty=pageModule.value==='hair'&&beauty.value;draft.preferences=[selected.value.length?`期望方向：${selected.value.join('、')}`:'',`时间投入：${effort.value}`,note.value?`保留或避免：${note.value}`:''].filter(Boolean).join('；');uni.navigateTo({url:`/pages/upload/index?module=${pageModule.value}&session=${sessionId}`})}
</script>

<style scoped>.consult-page{display:grid;min-height:100vh}.main{padding:20px 22px 90px}.stepbar{display:flex;justify-content:flex-end;align-items:center;gap:20px;margin:30px 0;color:#777;font-family:"Songti SC",serif;text-align:center}.stepbar i{width:40px;height:1px;background:#bbb}.stepbar .active{color:var(--wine);border-bottom:2px solid;padding-bottom:8px}.form{max-width:1050px;margin:30px auto}.form section{display:grid;grid-template-columns:48px 1fr;border-top:1px solid var(--line);padding:28px 0}.idx{font-family:serif;font-size:27px;font-style:italic}.styles{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:20px}.style{position:relative;height:175px;color:white;overflow:hidden;cursor:pointer;transition:transform .32s cubic-bezier(.2,.75,.25,1),box-shadow .32s ease}.style image,.shade{position:absolute;inset:0;width:100%;height:100%}.style image{transform:scale(1.01);transition:transform .52s cubic-bezier(.2,.75,.25,1),filter .35s ease}.shade{background:linear-gradient(transparent,rgba(0,0,0,.72));transition:background .35s ease}.style-name,.style small,.selected-mark,.selected-projection{position:absolute;z-index:2;left:17px}.style-name,.style small{transition:transform .32s cubic-bezier(.2,.75,.25,1)}.style-name{bottom:37px;font-family:"Songti SC",serif;font-size:20px}.style small{bottom:17px}.selected-mark{display:none;top:12px;padding:5px 9px;background:rgba(255,255,255,.88);color:#272a2f;font-size:11px;letter-spacing:1px}.selected-projection{display:none;z-index:1;left:12px;bottom:42px;font-family:"Songti SC",serif;font-size:20px;color:rgba(255,255,255,.28);text-shadow:-3px -3px 7px rgba(255,255,255,.16);filter:blur(.35px);white-space:nowrap}.chosen{box-shadow:inset 0 0 0 3px #f3f4f6,0 0 0 1px #757a82;transform:translateY(-2px)}.chosen .selected-mark,.chosen .selected-projection{display:block}@media(hover:hover) and (pointer:fine){.style:hover{z-index:2;transform:translateY(-6px);box-shadow:0 16px 30px rgba(20,23,28,.24)}.style:hover image{transform:scale(1.085);filter:grayscale(1) contrast(1.06)}.style:hover .shade{background:linear-gradient(transparent 24%,rgba(0,0,0,.84))}.style:hover .style-name,.style:hover small{transform:translateY(-4px)}.style.chosen:hover{transform:translateY(-6px);box-shadow:inset 0 0 0 3px #f3f4f6,0 16px 30px rgba(20,23,28,.24)}}.style:active{transform:scale(.985)}.time-options{display:grid;grid-template-columns:1fr 1fr;margin-top:18px;border:1px solid var(--line)}.time-options text{text-align:center;padding:16px 8px;border:1px solid transparent;cursor:pointer}.time-options .active{background:linear-gradient(145deg,#fff,#dfe2e6);border-color:#aeb2b8}.footer{display:flex;align-items:center;gap:10px;border-top:1px solid var(--line);padding-top:24px}.spacer{flex:1}@media(min-width:900px){.consult-page{grid-template-columns:430px 1fr}.main{padding:20px 48px 45px}.styles{grid-template-columns:repeat(4,1fr)}.time-options{grid-template-columns:repeat(4,1fr)}.style{height:210px}}</style>
