/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    ConsultationAside: typeof import('./components/ConsultationAside.vue')['default']
    StepHeader: typeof import('./components/StepHeader.vue')['default']
    WdCheckbox: typeof import('@wot-ui/ui/components/wd-checkbox/wd-checkbox.vue')['default']
    WdSwitch: typeof import('@wot-ui/ui/components/wd-switch/wd-switch.vue')['default']
    WdTextarea: typeof import('@wot-ui/ui/components/wd-textarea/wd-textarea.vue')['default']
  }
}
